import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import 'dotenv/config';

const vaultPath = process.env.OBSIDIAN_VAULT_PATH;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source code, please visit the repository of this plugin.
*/`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        {
            name: 'obsidian-deploy',
            setup(build) {
                build.onEnd(() => {
                    if (!vaultPath) return;

                    const home = process.env.USERPROFILE || process.env.HOME || "";
                    const fullPath = path.isAbsolute(vaultPath) 
                        ? vaultPath 
                        : path.join(home, vaultPath);

                    try {
                        if (fs.existsSync(path.dirname(fullPath))) {
                            if (!fs.existsSync(fullPath)) fs.mkdirSync(fullPath, { recursive: true });

                            fs.copyFileSync("main.js", path.join(fullPath, "main.js"));
                            fs.copyFileSync("manifest.json", path.join(fullPath, "manifest.json"));
                            
                            if (fs.existsSync("styles.css")) {
                                fs.copyFileSync("styles.css", path.join(fullPath, "styles.css"));
                            }
                            console.log(`✅ Build successfully deployed to: ${fullPath}`);
                        }
                    } catch (err) {
                        console.error(`⚠️ Failed to deploy build: ${err.message}`);
                    }
                });
            },
        },
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}